brew cask install appcleaner
brew cask install visual-studio-code
brew cask install google-chrome
brew cask install imageoptim
brew cask install iterm2
brew cask install slack
brew cask install sourcetree
brew cask install boostnote
brew cask install firefox
brew cask install docker
